# Linear Algebra with NumPy and SciPy

In [2]:
import numpy as np
 
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])
 
# Rank of a matrix
print("Rank of A:", np.linalg.matrix_rank(A))

Rank of A: 3


In [3]:
 
# Determinant of a matrix
print("\nDeterminant of A:", np.linalg.det(A))
 
# Inverse of matrix A
print("\nInverse of A:\n", np.linalg.inv(A))
 
#print("\nMatrix A raised to power 3:\n",
#           np.linalg.matrix_power(A, 3))


Determinant of A: -306.0

Inverse of A:
 [[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


The trace of a square matrix is the sum of its diagonal entries.

![tr](https://media.geeksforgeeks.org/wp-content/uploads/20221119211255/tm2.jpg)

In [4]:
# Trace of matrix A
print("\nTrace of A:", np.trace(A))


Trace of A: 11


In [5]:
# dot product
np.dot([3,2,6],[1,7,-2]) 

5

In [6]:
#bigger arrays

a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]]) 
print(a,'\n',b)

[[1 2]
 [3 4]] 
 [[11 12]
 [13 14]]


In [7]:
np.dot(a,b)

array([[37, 40],
       [85, 92]])

In [8]:
# Create matrices a and b.
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

# Matrix multiplication using numpy.matmul()
result = np.matmul(a, b)

# Print the result.
print(result)

[[19 22]
 [43 50]]


**Difference between `matmul` and regular multiplication**
- `matmul` is a function, while the multiplication symbol is an operator. This means that matmul takes two arguments, while the multiplication symbol only takes one.
- `matmul` can be used to perform matrix multiplication on any two arrays, regardless of their shape. The multiplication symbol can only be used to perform matrix multiplication on arrays that have the same shape.
- `matmul` is more efficient than the multiplication symbol. This is because matmul uses a specialized algorithm to perform matrix multiplication.

In [9]:
a * b

array([[ 5, 12],
       [21, 32]])

In [10]:
# Using the NumPy function to find the transpose

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

transposed_arr = np.transpose(arr)

print("Original array:")
print(arr)

print("Transposed array:")
print(transposed_arr)

Original array:
[[1 2 3]
 [4 5 6]]
Transposed array:
[[1 4]
 [2 5]
 [3 6]]


In [11]:
#shortcut
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [12]:

# Create a 3x3 identity matrix 

identity_matrix = np.identity(3) 

print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
a = np.random.randn(2,3) #randomly gneerate 2 x 3 matrix
a

array([[-0.39977163, -0.15150347,  0.14701712],
       [ 0.36599509,  1.00972339, -0.33945665]])

## Using SciPy

In [14]:
#get the norm of a vector
from scipy import linalg
v = [-1, -2, 3, 4, 5]
linalg.norm(v)

7.416198487095663

In [15]:
tw_d_arr = np.array([[4,5], [3,2]])
tw_d_arr

array([[4, 5],
       [3, 2]])

In [16]:
#get the determeinant of the array
linalg.det(tw_d_arr)

-7.0

## Determinant Exercise

**Formulate the following** </br>
We have a certification test with 30 questions that are in total worth 150 points. They consist of two parts:
1. T or F questions are worth 4 points each
2. Multiple-choice questions are worth 9 points each

How many questions do we have for each type?


Assumptions:
 
- Let x be the num of T/F questions
- Let y be the num of multi-choice questions

Then:
 
$x + y = 30$
 
$4x + 9y = 150$

In [17]:
#grab the constants of the left side of each equation and place them in a matrix
VarM = np.array([[1,1], 
                 [4,9]])
print(VarM)

[[1 1]
 [4 9]]


In [18]:
# define the right side of the equation (values)
ValM = np.array([30,150])
print(ValM)

[ 30 150]


In [20]:
np.linalg.solve(VarM,ValM)

array([24.,  6.])

In [19]:
# using scipy
linalg.solve(VarM,ValM)

array([24.,  6.])

### Eigenvalues and Eigenvectors:

In [21]:
import numpy as np

# Create a matrix A
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Find the eigenvalues and eigenvectors of A
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues of A:", eigenvalues)
print("Eigenvectors of A:")
print(eigenvectors)


Eigenvalues of A: [ 1.61168440e+01 -1.11684397e+00 -8.58274334e-16]
Eigenvectors of A:
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


## Application in DS and ML (Advanced)

Eigenvalues and eigenvectors are fundamental concepts in linear algebra that have a wide range of applications in artificial intelligence (AI). They are particularly useful in machine learning and signal processing tasks.

**Eigenvalues** represent the scaling factors by which a linear transformation, such as a matrix multiplication, maps vectors to other vectors. They are analogous to the principal components of a dataset, indicating the directions of maximum variance in the data. In machine learning, eigenvalues are used for feature extraction, dimensionality reduction, and clustering. For instance, principal component analysis (PCA) utilizes eigenvalues to identify the most significant features in a dataset, reducing its dimensionality while preserving the most important information.

**Eigenvectors**, on the other hand, represent the directions along which the linear transformation operates. They provide insights into the inherent structure of the data and can be used to identify patterns and relationships between different data points. In AI, eigenvectors are employed for various tasks, including:

1. **Feature Extraction:** Eigenvectors can be used to extract the most important features from a dataset, helping to reduce noise and improve the performance of machine learning algorithms.

2. **Dimensionality Reduction:** By identifying the eigenvectors corresponding to the largest eigenvalues, we can reduce the dimensionality of a dataset while retaining the most relevant information. This can be particularly useful for high-dimensional datasets where computational resources are limited.

3. **Clustering:** Eigenvectors can be used to group data points into clusters based on their similarities, aiding in unsupervised learning tasks.

4. **Pattern Recognition:** Eigenvectors can be used to identify patterns and relationships in data, which is crucial for tasks like image and speech recognition.

5. **Signal Processing:** Eigenvectors play a vital role in signal processing techniques like filtering and compression.

In summary, eigenvalues and eigenvectors are powerful tools for analyzing data and extracting meaningful information. Their applications in AI span a wide range of tasks, making them essential for various machine learning and signal processing applications.

**Example 1: Feature Extraction Using PCA**

In [ ]:
import numpy as np
from sklearn.decomposition import PCA

# Create a dataset
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

# Perform PCA using 2 principal components
pca = PCA(n_components=2)
transformed_data = pca.fit_transform(data)

# Extract the principal components
principal_components = pca.components_

print("Principal Components:")
print(principal_components)

This example demonstrates how PCA, a technique based on eigenvalues and eigenvectors, is used to identify the two most significant features (principal components) in the dataset.

**Example 2: Dimensionality Reduction Using Eigenvectors**

In [3]:
import numpy as np

# Create a dataset
data = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])

# Calculate the covariance matrix
covariance_matrix = np.cov(data.T)

# Compute the eigenvalues and eigenvectors of the covariance matrix
w, v = np.linalg.eig(covariance_matrix)

# Sort the eigenvalues and eigenvectors in descending order
sorted_indices = w.argsort()[::-1]
sorted_eigenvectors = v[:, sorted_indices]

# Select the top 2 eigenvectors for dimensionality reduction
reduced_data = data @ sorted_eigenvectors[:, :2]

print("Reduced Data:")
print(reduced_data)

Reduced Data:
[[ -6.70820393  -0.32327544]
 [-17.88854382  -0.32327544]
 [-29.06888371  -0.32327544]]


This example illustrates how eigenvectors can be used to reduce the dimensionality of the dataset from five features to two, preserving the most important information.



**Example 3: Clustering Using Eigenvectors**

In [2]:
import numpy as np
from sklearn.cluster import KMeans

# Create a dataset
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

# Perform k-means clustering using 2 clusters
kmeans = KMeans(n_clusters=2, n_init='auto')
kmeans.fit(data)

# Extract the cluster centroids
centroids = kmeans.cluster_centers_

print("Cluster Centroids:")
print(centroids)

Cluster Centroids:
[[ 2.5  3.5  4.5]
 [ 8.5  9.5 10.5]]


This example demonstrates how eigenvectors can be used to initialize the cluster centroids in k-means clustering, which can improve the convergence and performance of the algorithm.

These examples provide a glimpse into the diverse applications of eigenvalues and eigenvectors in Python and AI. They are powerful tools for extracting meaningful information from data and solving various machine learning and signal processing problems.