# Linear Algebra

1. Introduction
2. Scalers and Vectors
3. Vector Operations
    - Arithmetics
    - Norm of a vector
4. Matrices
    - Arithmetics
    - Rank of a matrix
    - Inverse
    - Determinants
    - Identity Matrix
5. Eigenvectors and Eigenvalues

In [2]:
import numpy as np

## Introduction
### What is Linear Algebra?
- It's a branch of mathematics and helps with having a deep understanding of data science and machine learning concepts.
- In Lin Alg data is represented by scalers, vectors, and matrices with linear equations

## Scalers and Vectors
 - **Scalar** it's a 0-dimensional object and represents magnitude or measurement. e.g. length, area, weigth, speed, etc... geometrically, it's a point
 - **Vector** it's a 1-dimensional object and represents direction and magnitude. geometrically, it's a line with a direction. Examples:
    - Wind velocity vector has speed (magnitude) and direction of the wind. 15 miles/hour northeast
    - Gravity has a direction and magnitude
- You can convert a vector ito a scalar (extract the magnitude) using the norm function

### Vector operations
#### Adding Vectors

![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_06_Maths_and_Stats/Linear_Algebra/Image_3.png)


#### Multiplying Vectors


![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_06_Maths_and_Stats/Linear_Algebra/Image_4.png)

> We have 2 types of vector multiplications: **Dot Product** and **Cross Product**

![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_06_Maths_and_Stats/Linear_Algebra/Image_6.png)

Comparison:
- Dot Product:
    - The result is always a scaler.
    - Also called a scaler product.
    - Mathematical Applications:
        - Finding the angle between vectors
        - Project one vector onto another
    - Machine Learning Application:
        - Cosine Similarity used in recommender systems
        - Neural Networks - to process the weight values of a neuron
        - Word Embeddings - tokenization (processing and encoding words into numeric representation in a vector)
- Cross Product:
    - The result is always a vector.
    - The resulting vector is always perpendicular to both input vectors (it works in 3D space)
    - ML Application:
        - Computer Vision: cross product helps calculate the orientation of objects in 3D space
        - Self-driving Cars: orientation and surrounding objects
        - automation in making cars
        - Drones for asset inspections

> Both vectors have to be of the same size in order for the operations to work.

In [3]:
a = [4,6,7]
b = [8,9,2]

In [4]:
np.dot(a,b)

100

In [5]:
np.cross(a,b)

array([-51,  48, -12])

In [6]:
np.add(a,b)

array([12, 15,  9])

In [7]:
a + b # using + will concat the vectors

[4, 6, 7, 8, 9, 2]

In [8]:
np.subtract(a,b)

array([-4, -3,  5])

### Norm of a Vector

- It calculates the magnitude of a vector (a measurement of length)
- It's always a positive value
- Machine Learning Applications:
    - Regularization Process: L1 and L2 regularization use vector norms to penalize large weights to reduce overfitting.
    - Distance Measurements: Between data points for clustering analysis.
 
![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_06_Maths_and_Stats/Linear_Algebra/Image_8.png)

In [9]:
a = [7,5,8]
#using linalg sub-module
a_mag = np.linalg.norm(a)
a_mag

11.74734012447073

11.75 is the magnitude of vector [7,5,8]

In [10]:
# calculate the direction
a_dir = a/a_mag
a_dir

array([0.59587957, 0.42562827, 0.68100522])

Wind Speed and Direction Vector Example

In [11]:
#vector
v = [4, 7]

#magnitude (speed)
print('speed:',np.linalg.norm(v))
print('Direction (Unit Vector):', np.array(v)/np.linalg.norm(v))
#for angle, get the arctan between 2 vectors

speed: 8.06225774829855
Direction (Unit Vector): [0.49613894 0.86824314]


## Matrices

- It's a rectangular array of numbers or expressions, arranged in columns or rows (2D).

![sh](https://res.cloudinary.com/practicaldev/image/fetch/s--8pw60d5S--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_800/https://raw.githubusercontent.com/adhiraiyan/DeepLearningWithTF2.0/master/notebooks/figures/fig0201a.png)

In [12]:
m = np.array([[5,6,3],[9,4,2]])
m

array([[5, 6, 3],
       [9, 4, 2]])

In [13]:
m.ndim

2

In [14]:
m.shape

(2, 3)

### Matrix Operations

- Dot Product and Element-Wise Product of Matrices Application:
    - Neural Network Operations
    - Attention Mechanism and Transform Operations in GPT-based models

![m](https://i.ytimg.com/vi/d6lIaqQI0UE/sddefault.jpg)

![matrizmulti1.PNG](https://s3.us-east-1.amazonaws.com/static2.simplilearn.com/lms/testpaper_images/ADSP/Advanced_Statistics/LinearRegression/matrizmulti1.PNG)

Square Matrix: num of rows = num of columns

In [15]:
a = np.array([[5,6,7],[3,4,7], [6,6,2]])
b = np.array([[3,4,1],[3,2,2], [4,6,9]])

In [ ]:
#dot prod
np.matmul(a,b)

array([[61, 74, 80],
       [49, 62, 74],
       [44, 48, 36]])

In [17]:
#different syntax
a @ b

array([[61, 74, 80],
       [49, 62, 74],
       [44, 48, 36]])

In [18]:
np.dot(a,b)

array([[61, 74, 80],
       [49, 62, 74],
       [44, 48, 36]])

In [ ]:
#element wise
a * b

array([[15, 24,  7],
       [ 9,  8, 14],
       [24, 36, 18]])

### Rank of A Matrix

- Machine Learning Applications:
    - Dimensionality Reduction: PCA 
    - Feature Selection: Rank-based method for selecting the most impactful features in the data based on an ML model
    - Image Compression
- To calculate the rank of a matrix, you do 2 steps:
    1. Transform the matrix into a row-echelon form
    2. Count the number of non-zero rows 

![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_06_Maths_and_Stats/Linear_Algebra/Image_11.png)

__Example__

![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_06_Maths_and_Stats/Linear_Algebra/Image_12.png)

The output, after using elementary transformations, is shown below:

**R2 → R2 – 2R1**

**R3 → R3 – 3R1**

![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_06_Maths_and_Stats/Linear_Algebra/Image_13.png)

**R3 → R3 – 2R2**

![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_06_Maths_and_Stats/Linear_Algebra/Image_14.png)

The above matrix is in row-echelon form.

Since the number of non-zero rows is 2,



**The rank of the matrix is 2.**

In [20]:
m = np.array([[1,2,3],
            [2,1,4],
            [3,0,5]])

In [21]:
print('Rank of the matrix:',np.linalg.matrix_rank(m))

Rank of the matrix: 2


### Determinant and Trace of A Matrix

- The determinant of a matrix is a scaler representation (quantity) that is a function of the elements of the matrix.
- Applications:
    - They are used to solve for linear equations
    - Used for optimization
- For 2x2 and 3x3 matrices:
 
![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_06_Maths_and_Stats/Linear_Algebra/Image_16.png)

In [29]:
m = np.array([[[5,6,7],[3,4,8],[6,6,9]]])

In [30]:
print('Determinant of the matrix:', np.linalg.det(m))

Determinant of the matrix: [24.]


The trace of a square matrix is the sum of its diagonal entries.</br>
![tr](https://media.geeksforgeeks.org/wp-content/uploads/20221119211255/tm2.jpg)

In [31]:
print('Trace of the matrix:', np.trace(m))

Trace of the matrix: [5 6 7]


### Identity Matrix

- An identity matrix (I) is a square matrix that, when multiplied by another matrix M, it gives the same results as M.
$$I*M = M*I = M$$
- This is similar to multiplying a number by 1. 5 x 1  = 5
- The diagonal elements of I are all 1, and the non-diagonal elements are all zeroes.
- Application in ML:
    - Neural Networks: they use identity matrices to initialize weight values.
    - Residual Connection in Neural Networks

Example:
 
![det4.PNG](https://s3.us-east-1.amazonaws.com/static2.simplilearn.com/lms/testpaper_images/ADSP/Advanced_Statistics/LinearRegression/det4.PNG)

In [32]:
# create a 3x3 ident matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### The Inverse of A Matrix
- symbol: $A^{-1}$
- It's a matrix when multiplied by its original matrix, you get an identity matrix
    - Note: The rank of a matrix should match the number of rows and columns (3x3 matrix should have rank 3)
- if the inverse of a matrix is not possible, it means the matrix is singular. To find out if it's singular or not, calculate the determinant and if it's zero, then it's singular.


In [33]:

a_inv = np.linalg.inv(a)
a_inv

array([[[-0.5       , -0.5       ,  0.83333333],
        [ 0.875     ,  0.125     , -0.79166667],
        [-0.25      ,  0.25      ,  0.08333333]]])

In [34]:
Iden = np.matmul(a,a_inv).astype('float64')
Iden

array([[[ 1.00000000e+00, -2.77555756e-16,  2.49800181e-16],
        [ 2.22044605e-16,  1.00000000e+00, -2.22044605e-16],
        [ 4.99600361e-16,  5.55111512e-17,  1.00000000e+00]]])

## Eigenvectors and Eigenvalues

- Think of a matrix as a machine that transforms a vector when multiplied by it. Some special vectors, called eigenvectors, don’t change their direction when this transformation happens. They only get stretched or shrunk by a special number called an eigenvalue.
- Eigenvalues are a set of scaler values used to represent the linear equations in matrix operations.
- Imagine having a box and you're asked to stretch or compress everything inside the box, but only in a certain direction. Eigenvalues tell you how much everything stretches or compresses along the specified direction.
- Another analogy, eigenvectors and eigenvalues can be used to reduce a cube into a square that represents the original magnitude (with a certain level of information loss).
- Application:
    - Principal Component Analysis

![ev](https://i.ytimg.com/vi/TQvxWaQnrqI/hqdefault.jpg)

In [26]:
np.linalg.eig(m)

(array([ 7.27491722e+00, -2.74917218e-01,  2.33606334e-15]),
 array([[-0.49488135, -0.85437274, -0.81110711],
        [-0.57374795, -0.18423296, -0.32444284],
        [-0.65261454,  0.48590682,  0.48666426]]))