<h1 style="text-align:center"><span style="color:#4584b6"><span style="font-family:Times New Roman,Times,serif">Why Use</span></span>&nbsp;<span style="font-family:Lucida Sans Unicode,Lucida Grande,sans-serif"><span style="color:#ffffff"><strong><span style="background-color:#f1c40f">Python</span></strong></span></span><strong>&nbsp;<span style="font-family:Times New Roman,Times,serif">?</span></strong></h1>

<p style="text-align:center"><img alt="" src="https://img.freepik.com/free-icon/snakes_318-368381.jpg" style="height:200px; width:200px" /></p>

<p style="text-align:center"><span style="font-size:14px">for Data Analysis &amp; Visualization</span></p>

<p style="text-align:center"><span style="color:#7f8c8d"><em><span style="font-size:11px">by Bassel Dakhlallah</span></em></span></p>


---

Here are some key reasons why Python is great for data analysis and visualization:

- **Wide Range of Libraries:** Python offers powerful libraries like Pandas for data manipulation and analysis, NumPy for numerical computations, and Matplotlib, Seaborn, and Plotly for data visualization. These libraries provide efficient tools for handling data and creating insightful visualizations.

- **Data Handling Capabilities:** Python's Pandas library provides DataFrame structures, akin to database tables, making it easy to load, manipulate, and transform data. This is crucial for tasks like data cleaning, merging, aggregation, and reshaping.

- **Readability** - Python code is easy to read and understand compared to other languages. Makes exploratory analysis simpler.

- **Interactive shells** - Jupyter notebooks allow mixing code, visualizations and documentation in a live environment. Great for analysis. 

- **Versatile Visualization Options:** Python libraries offer a variety of visualization techniques, from basic bar charts and scatter plots to advanced interactive visualizations or publication-quality plots.

- **Scalability** - Python scales well from small scripts to large applications with libraries like NumPy and Pandas.

- **Large & Active community** - As a popular language, there are many resources and libraries being developed for scientific computing.

- **Industry adoption**- Python's data capabilities have made it a standard at many technology companies and research institutions.

- **Automation** - Python is also extremely useful for data pipeline and software automation tasks.


![tag](https://i0.wp.com/makemeanalyst.com/wp-content/uploads/2017/09/Python-libraries-for-data-analysis.png?resize=680%2C286)

In [2]:
import numpy as np
import pandas as pd

# Indexing, Slicing, & Filtering

![df](https://indhumathychelliahcom.files.wordpress.com/2020/09/e1abc-1cuhnqwnicnwipgkzqo91bg.png)

# Imputation

- Using arbitrary, mean, median
- Using advanced techniques: KNN (useful for location and other member/rovider attributes)

# Reshaping Data

## Data Rearrangement

In [3]:
arr = np.arange(6).reshape(2,3) 
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [4]:
arr.ravel()

array([0, 1, 2, 3, 4, 5])

## Encoding

## Ordinal Encoding
![enc](https://miro.medium.com/v2/resize:fit:1358/1*ggtP4a5YaRx6l09KQaYOnw.png)

## Ordinal Encoding
![enc2](https://www.scaler.com/topics/images/ordinal-encoding-thumbnail.webp)

## Melt, Stack, and Unstack

### Melt
![ml](https://pandas.pydata.org/docs/_images/reshaping_melt.png)

![st](https://devopedia.org/images/article/306/2459.1610691355.png)

## Transpose

In [5]:
students = {
    'Name' : ['Mark', 'Alex', 'John', 'Amy', 'Steve', 'Ally', 'Kelly', 'Todd'],
    'Score' : [40, np.NaN, 44, np.NaN, 26, 39, 42, np.NaN],
    'University' : ['UTC', 'CalTech', 'MSU', 'MIT', 'CalTech', 'None', 'CalTech', 'None'],
}
  
# creating a Dataframe object
 
df = pd.DataFrame(students)
df

Name  Score University
0   Mark   40.0        UTC
1   Alex    NaN    CalTech
2   John   44.0        MSU
3    Amy    NaN        MIT
4  Steve   26.0    CalTech
5   Ally   39.0       None
6  Kelly   42.0    CalTech
7   Todd    NaN       None

In [13]:
df_tran = df.T
df_tran


0        1     2    3        4     5        6     7
Name        Mark     Alex  John  Amy    Steve  Ally    Kelly  Todd
Score       40.0      NaN  44.0  NaN     26.0  39.0     42.0   NaN
University   UTC  CalTech   MSU  MIT  CalTech  None  CalTech  None

In [16]:
new_column_names = {old_col: f"Student_{old_col+1}" for old_col in df_tran.columns}
df_tran.rename(columns=new_column_names, inplace=True)
df_tran

Student_1 Student_2 Student_3 Student_4 Student_5 Student_6  \
Name            Mark      Alex      John       Amy     Steve      Ally   
Score           40.0       NaN      44.0       NaN      26.0      39.0   
University       UTC   CalTech       MSU       MIT   CalTech      None   

           Student_7 Student_8  
Name           Kelly      Todd  
Score           42.0       NaN  
University   CalTech      None

# Generating Data

In [7]:
np.linspace(1, 10, num=5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

`pd.date_range()` - Generate a DatetimeIndex for a time series

In [9]:
pd.date_range('1/1/2020', periods=365)

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10',
               ...
               '2020-12-21', '2020-12-22', '2020-12-23', '2020-12-24',
               '2020-12-25', '2020-12-26', '2020-12-27', '2020-12-28',
               '2020-12-29', '2020-12-30'],
              dtype='datetime64[ns]', length=365, freq='D')

In [8]:
pd.period_range('2000Q1', periods=20, freq='Q')

PeriodIndex(['2000Q1', '2000Q2', '2000Q3', '2000Q4', '2001Q1', '2001Q2',
             '2001Q3', '2001Q4', '2002Q1', '2002Q2', '2002Q3', '2002Q4',
             '2003Q1', '2003Q2', '2003Q3', '2003Q4', '2004Q1', '2004Q2',
             '2004Q3', '2004Q4'],
            dtype='period[Q-DEC]')

In [12]:
pd.DataFrame(np.random.rand(10, 5), columns=list('abcde'))

a         b         c         d         e
0  0.431294  0.140228  0.368541  0.990337  0.639486
1  0.677761  0.575056  0.982980  0.025667  0.262671
2  0.565754  0.446556  0.319149  0.796126  0.814799
3  0.349710  0.804601  0.435573  0.175279  0.085766
4  0.578116  0.003691  0.700784  0.098296  0.487931
5  0.067781  0.385056  0.520785  0.387470  0.831863
6  0.779358  0.657431  0.070469  0.298807  0.326452
7  0.658861  0.769584  0.320196  0.524117  0.752142
8  0.662738  0.484470  0.215829  0.422789  0.719966
9  0.477083  0.394499  0.319306  0.255363  0.591338

In [17]:
pd.Series(np.random.randn(5))

0    0.080423
1   -0.607007
2    0.557367
3   -0.898187
4   -0.262319
dtype: float64

You can generate a sequence in Pandas using pd.Series and specifying a start, end, and step size:

In [19]:
start = 10
end = 50
step = 5
seq = pd.Series(range(start, end+1, step))
seq

0    10
1    15
2    20
3    25
4    30
5    35
6    40
7    45
8    50
dtype: int64

# Advanced Data Pull and Reshaping

In [22]:
# Create a sample DataFrame
data = {'Category': ['A', 'B', 'A', 'C', 'B', 'D', 'C'],
        'Value': ['Sam', 'Mark', 'Mike', 'Sam', 'Mary', 'Nancy', 'Brandon']}
df = pd.DataFrame(data)

# Get distinct values for multiple columns
distinct_values = df.drop_duplicates(subset=['Category', 'Value'])

distinct_values.sort_values(by=['Category','Value'])


Category    Value
2        A     Mike
0        A      Sam
1        B     Mark
4        B     Mary
6        C  Brandon
3        C      Sam
5        D    Nancy

In [24]:
import pandas as pd

# Create a sample DataFrame with spaces in column names
data = {'Column 1': [85, 90, 78],
        'Column 2': [95, 88, 92],
        'Column 3': [80, 87, 91]}
df = pd.DataFrame(data)

# Remove spaces from column names
df.columns = df.columns.str.replace(' ', '_')

df


Column_1  Column_2  Column_3
0        85        95        80
1        90        88        87
2        78        92        91

In [20]:
data_url = "http://lib.stat.cmu.edu/datasets/boston"
raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
raw_df.head()

0      1      2    3      4      5     6       7    8      9     10
0    0.00632  18.00   2.31  0.0  0.538  6.575  65.2  4.0900  1.0  296.0  15.3
1  396.90000   4.98  24.00  NaN    NaN    NaN   NaN     NaN  NaN    NaN   NaN
2    0.02731   0.00   7.07  0.0  0.469  6.421  78.9  4.9671  2.0  242.0  17.8
3  396.90000   9.14  21.60  NaN    NaN    NaN   NaN     NaN  NaN    NaN   NaN
4    0.02729   0.00   7.07  0.0  0.469  7.185  61.1  4.9671  2.0  242.0  17.8

In [22]:
#apply horizontal stacking to glue both arrays side by side
data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :3]])
# to just get the target
target = raw_df.values[1::2, 2]
boston_df = pd.DataFrame(data)
boston_df.head()

0     1     2    3      4      5     6       7    8      9     10  \
0  0.00632  18.0  2.31  0.0  0.538  6.575  65.2  4.0900  1.0  296.0  15.3   
1  0.02731   0.0  7.07  0.0  0.469  6.421  78.9  4.9671  2.0  242.0  17.8   
2  0.02729   0.0  7.07  0.0  0.469  7.185  61.1  4.9671  2.0  242.0  17.8   
3  0.03237   0.0  2.18  0.0  0.458  6.998  45.8  6.0622  3.0  222.0  18.7   
4  0.06905   0.0  2.18  0.0  0.458  7.147  54.2  6.0622  3.0  222.0  18.7   

       11    12    13  
0  396.90  4.98  24.0  
1  396.90  9.14  21.6  
2  392.83  4.03  34.7  
3  394.63  2.94  33.4  
4  396.90  5.33  36.2

In [23]:
#get col headers 
raw_cols = pd.read_csv(data_url, sep="\t", skiprows=range(0, 7), nrows=14, header=None)
raw_cols

0
0              CRIM     per capita crime rate by town
1    ZN       proportion of residential land zoned...
2    INDUS    proportion of non-retail business ac...
3    CHAS     Charles River dummy variable (= 1 if...
4    NOX      nitric oxides concentration (parts p...
5       RM       average number of rooms per dwelling
6    AGE      proportion of owner-occupied units b...
7    DIS      weighted distances to five Boston em...
8    RAD      index of accessibility to radial hig...
9    TAX      full-value property-tax rate per $10...
10               PTRATIO  pupil-teacher ratio by town
11   B        1000(Bk - 0.63)^2 where Bk is the pr...
12          LSTAT    % lower status of the population
13   MEDV     Median value of owner-occupied homes...

In [24]:
boston_df.columns = raw_cols[0].str.split().str.get(0)
boston_df.head()

0     CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

0  PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

# String Operations

![in](https://res.cloudinary.com/practicaldev/image/fetch/s--A7oqOWqx--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://thepracticaldev.s3.amazonaws.com/i/1wr90mjnil60r7226bgq.png)

### Multiple `if else` conditions

**syntax**
 
```python
#define conditions
conditions = [
    (df['column1'] == 'A') & (df['column2'] < 20),
    (df['column1'] == 'A') & (df['column2'] >= 20),
    (df['column1'] == 'B') & (df['column2'] < 20),
    (df['column1'] == 'B') & (df['column2'] >= 20)
]

#define results
results = ['result1', 'result2', 'result3', 'result4']

#create new column based on conditions in column1 and column2
df['new_column'] = np.select(conditions, results)
```

In [4]:
import pandas as pd

#create DataFrame
df = pd.DataFrame({'team': ['A', 'A', 'A', 'A', 'B', 'B', 'B', 'B'],
                   'points': [15, 18, 22, 24, 12, 17, 20, 28]})

df

team  points
0    A      15
1    A      18
2    A      22
3    A      24
4    B      12
5    B      17
6    B      20
7    B      28

- Bad_A if team is A and points < 20
- Good_A if team is A and points ≥ 20
- Bad_B if team is B and points < 20
- Good_B if team is B and points ≥ 20


In [3]:
import numpy as np

#define conditions
conditions = [
    (df['team'] == 'A') & (df['points'] < 20),
    (df['team'] == 'A') & (df['points'] >= 20),
    (df['team'] == 'B') & (df['points'] < 20),
    (df['team'] == 'B') & (df['points'] >= 20)
]

#define results
results = ['Bad_A', 'Good_A', 'Bad_B', 'Good_B']

#create new column based on conditions in column1 and column2
df['class'] = np.select(conditions, results)

#view updated DataFrame
df

team  points   class
0    A      15   Bad_A
1    A      18   Bad_A
2    A      22  Good_A
3    A      24  Good_A
4    B      12   Bad_B
5    B      17   Bad_B
6    B      20  Good_B
7    B      28  Good_B

RegEx

# Automation

# Visualization

- Ridgeline
- Sankey
- clustermap dendrograms
- Heatmap
- Pairplot
- Hex scatterplot
- Jitter
- Calendar