# __Introduction to Tensors__

Tensors are fundamental data structures in deep learning and are similar to multi-dimensional arrays. They are a generalization of vectors and matrices to higher dimensions and provide a way to represent and manipulate numerical data efficiently.

Tensors can be seen as containers for numerical data that can be organized into a specific shape or size.

Understanding tensor operations in TensorFlow is essential for effectively working with deep learning models in TensorFlow. Here's why:

1. **Foundation of TensorFlow**: Tensors are the fundamental data structures used in TensorFlow. All data, including inputs, model parameters, and outputs, are represented as tensors. Understanding how to create, manipulate, and operate on tensors is crucial for building and training neural networks in TensorFlow.

2. **Computation Graph**: TensorFlow uses a computation graph to represent the operations performed by a neural network. Tensors flow through the graph, undergoing various operations such as matrix multiplications, activations, and reductions. Understanding tensor operations allows you to construct and manipulate the computation graph effectively.

3. **Customization and Optimization**: Deep learning models often require customization and optimization to achieve the desired performance. TensorFlow provides a rich set of tensor operations and APIs for building custom layers, loss functions, and optimization algorithms. Understanding tensor operations enables you to customize and optimize your models according to specific requirements.

4. **Debugging and Troubleshooting**: When working with deep learning models, debugging and troubleshooting are common tasks. Understanding tensor operations allows you to inspect intermediate tensors, visualize the computation graph, and identify potential issues in your models.

While understanding how to deploy neural networks is also important, it typically builds upon a solid foundation of tensor operations. Deployment involves tasks such as model serialization, inference optimization, and integration with production systems, which may not require as deep an understanding of tensor operations as model development and training do.

In summary, learning tensor operations in TensorFlow is essential for effectively building, training, customizing, and troubleshooting deep learning models. It provides a solid foundation for working with TensorFlow and enables you to develop and deploy high-performance neural networks.


## Steps to Be Followed:
1. Importing the required libraries
2. Creating the rank zero Tensor
3. Creating the rank one Tensor
4. Creating the rank two Tensor
5. Creating the rank three Tensor
6. Converting a Tensor to a NumPy array
7. Performing basic mathematics with Tensors
8. Initializing the Tensor
9. Broadcasting the x and y variables

### Step 1: Importing the Required Libraries

- Two libraries, TensorFlow and NumPy, should be imported.
- TensorFlow is a popular open-source machine learning framework that provides a set of tools and functionalities for building and training machine learning models.
- NumPy is a Python library for numerical computations that provide support for handling multi-dimensional arrays and mathematical operations on them.

In [1]:
import tensorflow as tf
import numpy as np

In [18]:
print(tf.__version__) # find the version number (should be 2.x+)

2.13.0


### Step 2: Creating the Rank Zero Tensor
- The rank is also known as order, degree, or ndims.
- The **tf.constant(4)** creates a constant Tensor with a single value of **4**.
- The **tf.constant()** function is used to create Tensors with fixed values that cannot be changed.
- The **rank_0_tensor** variable holds the created Tensor.
- The **print(rank_0_tensor)** prints the value of the Tensor, which,  in this case, is __4__.

In [2]:
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


**Observation:**

- As seen above, the output represents a TensorFlow Tensor object with a value of 4, an empty shape, and an **int32** data type.

### Step 3: Creating the Rank One Tensor
- Define a rank one Tensor in TensorFlow with the values **[2.0, 4.0, 5.0]** and print the Tensor object

In [3]:
rank_1_tensor = tf.constant([2.0, 4.0,5.0]) # creating a vector with 1 dimension
print(rank_1_tensor)

tf.Tensor([2. 4. 5.], shape=(3,), dtype=float32)


**Observations:**

- As seen above, the output represents a one-dimensional Tensor with three elements: **2.0**, **4.0**, and **5.0**.
- The shape of the Tensor is **(3, ),** indicating that it has a size of 3 along the first dimension.
- The dtype of the Tensor is **float32**, indicating that the elements are of type float.

In [4]:
rank_1_tensor = tf.constant([2.0, 4.0,5.0], dtype='float64')
print(rank_1_tensor)

tf.Tensor([2. 4. 5.], shape=(3,), dtype=float64)


### Step 4: Creating the Rank Two Tensor
- It creates a rank two Tensor, which is a two-dimensional array, using the **tf.constant** function.
- The Tensor has a shape of (3, 2), meaning it has three rows and two columns, and the elements of the Tensor are specified as [1, 2], [3, 4], and [5, 6].

In [5]:
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.float16)

print(rank_2_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


**Observations:**

- The output represents a rank two Tensor with a shape of (3, 2) and a dtype of float16. The Tensor contains the following elements arranged in a 3x2 matrix, as seen above.
- Each element of the Tensor is a floating-point number with a precision of 16 bits.

In [6]:
rank_2_tensor.shape

TensorShape([3, 2])

You can always tell the size form the bracket count

### Step 5: Creating the Rank Three Tensor

- It defines a rank three Tensor with a shape of (3, 2, 5), indicating three layers, each containing two rows and five columns.
- The Tensor represents a 3D array of integers, where each element corresponds to a specific position within the layers, rows, and columns.
- The values increase sequentially from __0__ to __29__, arranged in a structured pattern within the Tensor.



In [7]:
rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])

print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


In [17]:
rank_3_tensor.ndim

3

**Observations:**
- The output represents a rank three Tensor with a shape of (3, 2, 5) and a data type of int32.
- It contains three layers, each consisting of two rows and five columns, with integer values ranging from 0 to 29 arranged in a structured pattern within the Tensor.


![difference between scalar, vector, matrix, tensor](https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/main/images/00-scalar-vector-matrix-tensor.png)

### Step 6: Converting a Tensor to a NumPy Array

- The rank two array present here is converted to a NumPy array.
- The Tensors often contain float datatype.

In [8]:
rank_2_tensor.numpy()

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)

**Observations:**
- The output represents a two-dimensional array (matrix) with a shape of (3, 2) and a data type of float16.
- It contains floating-point values ranging from 1.0 to 6.0, organized in three rows and two columns.
- You might want to convert to numpy for applications that are not compatible with TensorFlow

### Step 7: Performing Basic Mathematics on Tensors
- Declare two variables **a** and **b**.
- The **tf.add(a, b)** operation performs element-wise addition between Tensors a and b.
- The **tf.multiply(a, b)** operation performs element-wise multiplication between Tensors a and b.
- The **tf.matmul(a, b)** operation performs matrix multiplication between Tensors a and b.


In [9]:
a = tf.constant([[1, 2],
                 [3, 4]])
b = tf.constant([[1, 1],
                 [1, 1]])

print(tf.add(a, b), "\n")
print(tf.multiply(a, b), "\n")
print(tf.matmul(a, b), "\n")

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 



**Observations:**
- Tensors do element-wise addition and multiplication.
- The given output consists of three TensorFlow Tensors, each representing a 2x2 matrix with integer values.

### Indexing Tensor

In [30]:
a[0]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [31]:
# Will error (requires the .assign() method)
a[0][0]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

  ### Step 8: Initializing the Tensor

  - The **tf.reduce_max(c)** calculates the maximum value in Tensor c.
  - The **tf.math.argmax(c)** returns the index of the maximum value in Tensor c.
  - The **tf.nn.softmax(c)** applies the softmax activation function to Tensor c, which computes the probability distribution over the elements of c.


In [10]:
c = tf.constant([[4.0, 5.0], [10.0, 1.0]])
print(tf.reduce_max(c))
print(tf.math.argmax(c))
print(tf.nn.softmax(c))

tf.Tensor(10.0, shape=(), dtype=float32)
tf.Tensor([1 0], shape=(2,), dtype=int64)
tf.Tensor(
[[2.6894143e-01 7.3105860e-01]
 [9.9987662e-01 1.2339458e-04]], shape=(2, 2), dtype=float32)


**Observation:**
- It calculates the maximum value in Tensor c, finds the indices of the maximum values, and applies the softmax function to obtain a probability distribution Tensor.

### Step 9: Broadcasting the X and Y Variables
- Broadcast the two variables **x** and **y**.
- Smaller Tensors are stretched automatically to fit larger Tensors.
- All of these are the same computation.
- It performs element-wise multiplication between Tensors x and a scalar value of 2, between Tensors x and scalar y, and between Tensors x and Tensors z.

In [11]:
x = tf.constant([1, 2, 3])

y = tf.constant(2)
z = tf.constant([2, 2, 2])
print(tf.multiply(x, 2))
print(x * y)
print(x * z)

tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)


**Observations:**

- We can see that even though the shape of y is not the same as that of x, we can still multiply these two variables.
- So, this is an example of broadcasting, where smaller Tensors are stretched automatically to fit larger Tensors.

#### Reshaping Tensors

In [12]:
x = tf.constant([[1], [2], [3]])
print(x.shape)

(3, 1)


**Observation:**
- So, the shape function; returns
a tensor-shaped object that shows the size, along each axis.

In [13]:
reshaped = tf.reshape(x , [1,3])

In [32]:
reshaped

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[1, 2, 3]], dtype=int32)>

In [14]:
print(x.shape)
print(reshaped.shape)

(3, 1)
(1, 3)


**Observation:**
- The Tensor has been reshaped to the desired dimensions, providing the intended configuration.

### Generate Tensors

In [33]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros([2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [34]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # create a NumPy array between 1 and 25
A = tf.constant(numpy_A,  
                shape=[2, 4, 3]) # note: the shape total (2*4*3) has to match the number of elements in the array
numpy_A, A

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32),
 <tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18],
         [19, 20, 21],
         [22, 23, 24]]], dtype=int32)>)

#### Different Types of Tensors
- Ragged Tensor: Tensor with the variable number of
elements along some axes is called Ragged Tensor.

In [35]:
ragged_list = [
    [0,1,2,3],
    [4,5],
    [6,7,8],
    [9]]

ragged_tensor = tf.ragged.constant(ragged_list)
print(ragged_tensor)

<tf.RaggedTensor [[0, 1, 2, 3], [4, 5], [6, 7, 8], [9]]>


A ragged tensor is a type of tensor in TensorFlow that represents sequences of variable lengths. In contrast to regular tensors, which have fixed shapes for all dimensions, ragged tensors allow for dimensions to have varying lengths across different elements of the tensor. Ragged tensors are used to represent irregular or non-uniform data structures, such as sequences of different lengths, lists of varying sizes, or nested structures.

Here are some common use cases for ragged tensors:

1. **Natural Language Processing (NLP)**:
   - Ragged tensors are commonly used in NLP tasks where input sequences have variable lengths, such as text classification, sentiment analysis, or machine translation. Each element of the tensor corresponds to a sequence of words or tokens, and the lengths of these sequences can vary from one element to another.

2. **Time Series Data**:
   - In time series analysis, ragged tensors can represent sequences of data points with variable lengths. For example, financial data or sensor readings collected at irregular intervals may be represented using ragged tensors, where each element corresponds to a time series of varying length.

3. **Feature Representation**:
   - Ragged tensors can be used to represent feature vectors with variable numbers of elements. For instance, in feature engineering tasks where each data point has a different number of features, ragged tensors allow for efficient storage and processing of such data.

4. **Sparse Data**:
   - Ragged tensors are useful for representing sparse data structures where most elements are zero or missing. By only storing non-zero or non-missing elements along with their indices, ragged tensors can efficiently represent sparse matrices or tensors.

5. **Deep Learning Models**:
   - Ragged tensors can be used as inputs or outputs of deep learning models, especially in architectures such as recurrent neural networks (RNNs) or transformer models. These models can handle sequences of variable lengths, and ragged tensors provide a natural way to represent such data.

Overall, ragged tensors are a powerful tool in TensorFlow for working with irregular or non-uniform data structures, providing flexibility and efficiency in representing and processing data with variable lengths or shapes.

- Scalar String Tensor: It is a datatype, which means that data can be represented as strings (variable-length byte arrays) in Tensors.

In [16]:
scalar_string_tensor = tf.constant("gray wolf")
print(scalar_string_tensor)

tf.Tensor(b'gray wolf', shape=(), dtype=string)


**Observation**
- We can see that we can even represent
the strings as Tensors.
