- load the data using `loadtxt`
- get the shape
- convert the array into a 2d array
- build a new array with values less than 100
- calculate the mean, median, and SD


In [12]:
import numpy as np

# Reading a CSV file
data = np.loadtxt('num_data.csv', delimiter=',')
data


array([  9., 167.,  30.,  71., 102.,  87., 229., 227.,  91.,  78.,  84.,
       177.,  91.,  26., 226.,   7.,  92., 215., 185.,  86., 119., 191.,
        21., 182.,  53.,  70., 185., 129., 232.,  28., 106., 136.,  62.,
       168., 139., 154., 149., 125., 188.,  29., 180.,   7., 166., 228.,
        72.,  25., 114., 135.,  54., 208.,  33., 228., 125.,  82.,  69.,
        53., 218.,  90.,  52., 153., 101., 157., 160.,   9., 187.,  20.,
        93.,  42.,  65., 225.,  56.,  55.])

In [13]:
np.shape(data)

(72,)

In [18]:
data.reshape(9,8) 

array([[  9., 167.,  30.,  71., 102.,  87., 229., 227.],
       [ 91.,  78.,  84., 177.,  91.,  26., 226.,   7.],
       [ 92., 215., 185.,  86., 119., 191.,  21., 182.],
       [ 53.,  70., 185., 129., 232.,  28., 106., 136.],
       [ 62., 168., 139., 154., 149., 125., 188.,  29.],
       [180.,   7., 166., 228.,  72.,  25., 114., 135.],
       [ 54., 208.,  33., 228., 125.,  82.,  69.,  53.],
       [218.,  90.,  52., 153., 101., 157., 160.,   9.],
       [187.,  20.,  93.,  42.,  65., 225.,  56.,  55.]])

In [19]:
mask = np.where(data < 100)
filtered_array = data[mask]



In [20]:
filtered_array

array([ 9., 30., 71., 87., 91., 78., 84., 91., 26.,  7., 92., 86., 21.,
       53., 70., 28., 62., 29.,  7., 72., 25., 54., 33., 82., 69., 53.,
       90., 52.,  9., 20., 93., 42., 65., 56., 55.])